### ISSUE TITLE
"City Profiles" 

### ISSUE THREAD

**Issue by thekenz** [munirent/openprocure#10]
Eventually, I think it would be cool to refactor the website where there's a "City Profile" that pulls in different parts of the data table and organizes them into a profile of the city that's more accessible to end users.

**Comment by alan707** [comment]
Can you expand on this idea, @thekenz ?  Or better yet, close it and add it to the list of ideas for the feature roadmap: https://github.com/munirent/openprocure/wiki/Feature-Roadmap#ideas
