### ISSUE TITLE
Question about tackling different layers of thresholds inside an agency

### ISSUE THREAD

**Issue by alan707** [munirent/openprocure#13]
How can we incorporate the fact that there are different types of procurement thresholds.  For example in City of Palo Alto, Public Works contracts can be [approved up to $65,000](http://www.amlegal.com/nxt/gateway.dll/California/paloalto_ca/title2administrativecode*/chapter230contractsandpurchasingprocedur?f=templates$fn=default.htm$3.0$vid=amlegal:paloalto_ca$anc=JD_2.30.300) with an informal bid.  On the other hand any employee can [enter into a contract if it's less than $5,000](http://www.amlegal.com/nxt/gateway.dll/California/paloalto_ca/title2administrativecode*/chapter230contractsandpurchasingprocedur?f=templates$fn=default.htm$3.0$vid=amlegal:paloalto_ca$anc=JD_2.30.230).  And only purchasing managers can sign off contracts informally up to $25,000.

Something to think about.  Maybe we stick to the basics and close this issue.  Totally open for suggestions.

**Comment by monkbroc** [comment]
(It's kind of besides the point but both links to Palo Alto are broken.)

**Comment by alan707** [comment]
That American Legal Publishing website is not set up for the World Wide Web

**Comment by thekenz** [comment]
I think that down the line, we're going to need to look for patterns in purchasing regulations for different governments, and this in turn is going to affect how the database schema. 

In the meantime, my suggestion is to add both of these thresholds for record keeping purposes, and then describe them in the "notes" section, if we have them.

**Comment by alan707** [comment]
identified in issue#21 and added to idea list in feature roadmap wiki page: https://github.com/munirent/openprocure/wiki/Feature-Roadmap#ideas
