### ISSUE TITLE
Procurement Blog

### ISSUE THREAD

**Issue by thekenz** [munirent/openprocure#16]
I'd love to start drumming up some content for blog posts about why procurement reform is necessary in the form of short blog posts. These types of content could be great forms of media to post on social media to get more people interested in OpenProcure.

**Comment by alan707** [comment]
I think this is a good idea.  My recommendation is use Tumblr to get a blog up and running.  We can always link it to Open Procure or even use the blog.openprocure.us domain.  I will consider this issue closed.
