### ISSUE TITLE
Add in Purchasing Levels

### ISSUE THREAD

**Issue by thekenz** [munirent/openprocure#21]
Many of these cities have more than two purchasing levels -- ie not just regular purchasing vs. competitive bidding. 

From the [City of Charlotte's Website](http://www.charlottecountyfl.com/Purchasing/howto.asp):

> The County buys at three (3) different levels. The first level is anything of value less than $5,000 of which the requesting department has the responsibility and the authority to select the vendor and obtain pricing information. The second level is anything of value between $5,000 up to $50,000; a Request for Quotation is issued to three (3) or more vendors. The vendor exhibiting the best price, delivery, and/or additional criteria is awarded the order. The third level is for products or services valued at more than $50,000, official sealed bids are solicited and electronically posted on the County's website for at least ten (10) days before the dates set for receipt of bids, proposals or replies unless the Purchasing Division determines in writing that a shorter period of time is necessary to avoid harming the interest of the County. 

How would be describe these things in here?

**Comment by thekenz** [comment]
Adding in more information cities until we can figure out how to handle this: 

[City of Detroit's Purchasing Website](http://www.detroitmi.gov/How-Do-I/Do-Business-with-the-City/Items-Out-To-Bid-Information):

> The City of Detroit purchases goods and services under the following guidelines:
> 
> **Petty Cash** – (up to $399.99) only one quote is required.   Petty cash purchases are purchased and paid directly by the using department.
> **Imprest Cash** – ($400 – $1999.99) a minimum of three bids are required. Like Petty Cash, handled at departmental level, without approval from the Purchasing Division.
> **Informal Purchase** – ($2,000 – $25,000) handled through the Purchasing Division. There is no formal bid opening and only the successful bidder is notified of award.
> **Formal Purchase** – ($25,000.01 and above) handled through the Purchasing Division. A formal bid opening is held and all bidders are notified by letter to whom the award was made. The winning vendor cannot be in arrears with Detroit Income or Property Taxes and must receive a clearance from the Human Rights Department (for bids above $15,000). All formal purchases require the approval of the Detroit City Council. Vendors may protest a bid award by contacting the Purchasing Director by letter, prior to the City Council approval date.

**Comment by alan707** [comment]
Added to https://github.com/munirent/openprocure/wiki/Feature-Roadmap#ideas
