### ISSUE TITLE
How to handle different thresholds for different types of Services from the same Jurisdiction?

### ISSUE THREAD

**Issue by afomi** [munirent/openprocure#25]
Solano County, CA has logical conditions in its Procurement logic related to amount and type of service. Does OpenProcure handle/track this? If so, how?

Source: http://www.solanocounty.com/civicax/filebank/blobdload.aspx?blobid=12011

**Comment by afomi** [comment]
This https://github.com/munirent/openprocure/pull/24 is a great start!

Solano has 4 branches in its logic.  I'm wondering if and how consistent these thresholds and conditions are across jurisdictions.

**Comment by monkbroc** [comment]
Thanks for the input Ryan!

This is a great example where to apply the vague threshold definitions I
had in mind: below $10,000 for one written quote, above $25,000 for formal
sealed bids.

**Comment by alan707** [comment]
Ryan brings up a good point and something that is important to clearly explain.  The data shows there is no universal consistency, but in most cases there are three thresholds:
- up to $5,000 => no quotes required, can purchase direct.
- $5,000 - $25,000 => informal bid, 3 quotes usually required - sometimes can be oral quotes
- above $25,000 => formal bids

**Comment by monkbroc** [comment]
OK. You picked a different first threshold than me ($5k verbal quote vs $10k written quote) but we're all saying the same thing: there most often are 3 ranges, separated by 2 thresholds.

After I merge #24 we can work on clarifying what we think the thresholds should represent.

**Comment by alan707** [comment]
👍

—

**Comment by alan707** [comment]
fixed by #24
