### ISSUE TITLE
verify cities populations

### ISSUE THREAD

**Issue by alan707** [munirent/openprocure#3]
Search using this type of query to verify each city's population: https://www.google.com/?gws_rd=ssl#q=city+of+oakland+population

**Comment by jalbertbowden** [comment]
i guess this is related, so i didn't want to create a new issue, but alexandria, va does not have a population of 4 million that is shown here http://openprocure.us/?queries%5Bstate%5D=VA  
its actually around 148,892

**Comment by alan707** [comment]
good catch @jalbertbowden - update already pushed to master

**Comment by hellerpdx** [comment]
@carlvlewis what do you think about making the source of truth for population data whatever is displayed on [census reporter](https://censusreporter.org/)? Might be able to do something programmatically as well: https://github.com/censusreporter/census-api

**Comment by carlvlewis** [comment]
@hellerpdx I think that's a solid idea. We definitely need a definitively agreed-upon data point (which, as I think we've reached consensus, is the 2016 ACS estimates). And, sure, we can likely pull that data in programmatically . -- especially if the idea is to minimize the barrier to entry for contributions. The procurement data itself is the real goal -- using other existing data points to shed new light need not be something contributors dig up themselves.

I was also thinking about -- in addition to the GH PR method of contributing –– setting up a publicly editable Google Sheet to serve as an API, which contributors could easily update without having to know the Git workflow. Thoughts?

**Comment by hellerpdx** [comment]
@carlvlewis i can't think of any real downside to setting up the Google Sheet method of contributing. Regarding population, I think it's clearer to instruct to use Census Reporter to get the population number. Project documentation and comments now mention 2016 ACS estimates and to just google it.

**Comment by carlvlewis** [comment]
I'm actually not even sure we should ask for contributors to provide that
data. We can easily pull it in from anywhere programmatically.

What we can't easily get, however, are the procurement thresholds. That's
what we, I think, should refine the focus on for the project.

Thoughts?

**Comment by hellerpdx** [comment]
I agree, the focus should be on getting the thresholds. It makes sense to make adding the population part of our data pipeline instead of having the contributor look it up.

**Comment by carlvlewis** [comment]
@hellerpdx Sorry, thought I replied back here. Okay, in the new setup, which will use tabletop.js to pull in Google Sheets data as an API, I'm fundamentally confident in giving full edit access to the public, as Google Sheets has pretty thorough version control, as well as built-in notifications to sheet owners when changes are made to sheets. And the only fields we ask for are the thresholds, the name of the municipality, a URL to the source and the name of the contributor (we can also turn that into a Google form to provide another entry point for contributions).

*Addendum: At this point, I think we shouldn't let the scope go too broad to include all different types of agencies, as it then loses its focus sort of. I think we should focus first on getting data for the remaining 30 cities in the top 100 most populous U.S. cities by population. If anyone disagrees, feel free to speak now!*
