### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by carlvlewis** [munirent/openprocure#52]
While I recognize this project is far from comprehensive, it's definitely a step in the right direction for a very real problem, especially after having spoken in recent months to a number of municipal governments.

I notice the project has been stagnant for a while. Do you all plan to continue any work with it? If not, I will gladly volunteer to help maintain it if you all don't have the time/resources. Just let me know.

**Comment by alan707** [comment]
Carl, that would be amazing. We can make you the official maintainer. It would be nice to also set up an automated email that gets sent out to people that have subscribed to the list.

**Comment by alan707** [comment]
We've been pretty swamped lately and had zero time to carry the weight of improving/maintaining this super important Public asset.

**Comment by carlvlewis** [comment]
Sure, this actually very much falls in line with some academic research on municipal purchasing/smart city principals I’ve been working on lately, as well as my work as a Brigade Captain for Code for America. 

Procurement data standards are all over the place, and some attempt at standardization would be at least headed in the right direction. 

I can set up the automated email, no problem.

Just let me know the details for the subscriber list and such. I’m confident working with Middleman so that shouldn’t be an issue either.

CVL

**Comment by alan707** [comment]
Carl, just granted administrator rights to OpenProcure repo.  Thanks for keeping the lights going on this project.  Will reach out via email about subscriber list.

![image](https://cloud.githubusercontent.com/assets/1726205/24011126/185186ae-0a37-11e7-8844-b9294edc853e.png)

**Comment by carlvlewis** [comment]
Great. Going to tag this as civic-tech project seeking contributors to the Code for America network as well if that’s okay. Obviously can’t commit a huge amount of time myself, but will do my best.

And just for purposes of clarity, after significant additions/improvements are made, is it okay to update the README.md to say something along the lines of “A project originally conceived and built by MuniRent and <insert current contribs names here>. Project currently maintained by <Open Savannah> and the <Code for America> brigade network, along with <insert future contribs names here>”?

That’s jumping the gun obviously, but don’t want to give any appearance of hijacking MuniRent’s project and want to be clear that it’s not something we started just by ourselves.

**Comment by alan707** [comment]
Yes, definitely ok to tag as CfA project.  We are part of the CfA family (MuniRent is a CfA accelerator alumni) so go for it!  It would be good to add specific tags to issues so people can easily start contributing.

re: attribution plan after significant additions/improvements => 👍
