### ISSUE TITLE
"City Wishlist"

### ISSUE THREAD

**Issue by thekenz** [munirent/openprocure#6]
It would be really cool to have a running list of cities to be added to openprocure.us. Right now, because MuniRent is the primary "user" of the service, we should just build out the wishlist from the cities that MuniRent wants. 

If we get a sufficient amount of users down the line, it could be cool to "vote" on particular cities to be added, but that's for another feature request down the line. 

Also, I'm not sure if that list should live in Github Issues (someone opens an issue with "City Name", and we tag as a "wishlist city" or something), or on the website itself. 

What do you guys think?

**Comment by monkbroc** [comment]
GitHub has a wiki. It would be easy to make that list a wiki page

**Comment by alan707** [comment]
Easy to start a wiki: https://github.com/munirent/openprocure/wiki/Wish-List-of-Cities

**Comment by alan707** [comment]
moved to https://github.com/munirent/openprocure/wiki/Feature-Roadmap#ideas
