### ISSUE TITLE
add search methodology to readme.md

### ISSUE THREAD

**Issue by alan707** [munirent/openprocure#8]
As a new contributor, I'd like to know what search terms should I plug into Google to find out the procurement limits of a government agency.  Also it would be great to know other methodologies (e.g.: submitting a FOIA request to get the procurement limits of an agency).

**Comment by thekenz** [comment]
I can take this -- will add this tonight!

**Comment by alan707** [comment]
moved to https://github.com/munirent/openprocure/wiki/Feature-Roadmap#roadmap
