### ISSUE TITLE
Add Visualizations on top of this dataset

### ISSUE THREAD

**Issue by thekenz** [munirent/openprocure#9]
I'd love to have visualizations built on top of this dataset, such as map visualizations, bar / column chart visualizations, and pie visualizations.  Would be a really cool front-end project to take on.

**Comment by monkbroc** [comment]
You can import the CSV data in http://openprocure.us/procurement.csv directly to datasets in tools like Cartodb so that the visualization will auto-refresh

**Comment by thekenz** [comment]
Oh yeah! I've used tools like CartoDB to visualize datasets like this in the past. It would be awesome to embed those visualizations on the homepage of this website so people know how this data is being used.

**Comment by alan707** [comment]
@thekenz I like it.  This would be a great example showing how other applications use OpenProcure's data.  We can add a section on the homepage called `Example Apps` or `OpenProcure powers these apps` and in that section have links that have their own gh page containing the cartodb map, maybe a d3 visualization, etc.

**Comment by thekenz** [comment]
I think if we eventually want to be reaching out to media outlets with this dataset, this would be a really easy way for casual readers to immediately understand the data, and decide if they want to get involved or not.

**Comment by alan707** [comment]
transferred to ideas section of feature roadmap: https://github.com/munirent/openprocure/wiki/Feature-Roadmap#ideas
